### PR TITLE
update for newest version of U8glib_Arduino

### PR DESCRIPTION
**Pull request by iplayfast**

### CODE REVIEW

**Comment by oysteinkrog** [comment]
This needs to be rebased, currenly it is a mess.

**Comment by thinkyhead** [comment]
Is this backward-compatible for the older Arduino toolset? Does it matter to us going forward?

**Comment by Wackerbarth** [comment]
@thinkyhead -- This change replaces the direct inclusion of the c interface file with the inclusion of the c++ interface file. That file performs the above mentioned inclusion. Therefore, it should work on any compilation. Further, the loader should drop the c++ wrapper since it is not called.

Rebased version appears as the pr/93 branch

**Comment by Wackerbarth** [comment]
Merged

**Pull request closed without merging**
