### PR TITLE
Add Danish translations

### PR DESCRIPTION
**Pull request by Wackerbarth**
Moved from Marlin -- Awaiting @boelle  to confirm

### CODE REVIEW

**Comment by boelle** [comment]
in doubt about this one:

+#define MSG_VOLUMETRIC                      "Filament"

Volumetric got me thinking this one is wrong... "Filament" means just that... 

So what is it supposed to mean?

**Comment by boelle** [comment]
+#define MSG_STORE_EPROM                     "Gem i EEPROM"
+#define MSG_LOAD_EPROM                      "Hent fra EEPROM"

**Comment by boelle** [comment]
+#define MSG_WATCH                           "Info skærm"

**Comment by boelle** [comment]
+#define MSG_DWELL                           "Dvale..."

**Comment by boelle** [comment]
+#define MSG_ZPROBE_OUT                      "Sensor ausserhalb"

should this one mean that the prope is extended? not sure on the german explanation in quote's

**Comment by boelle** [comment]
anyways if these are updated etc i will look through again tomorrow

**Comment by Wackerbarth** [comment]
@boelle -- You need to enable our ability to add labels so that we can restore the labeling from Marlin.

**Comment by boelle** [comment]
oh just thought i should check translation and give feedback until i could give a thumbs up??

**Comment by Wackerbarth** [comment]
As for this file, you are welcome to just make the changes. My only involvement was to try to bring over the translations that were offered against 1.0.2.

The comment about labels has to do with site administration.  We don't have available the set of labels that we are using on Marlin. And I don't have the permissions to add them.

**Comment by boelle** [comment]
i tried to edit the file but did not have the edit option. will try again when i get up

anything i could do to give you the right permissions?

**Comment by AnHardt** [comment]
+#define MSG_ZPROBE_OUT "Sensor ausserhalb"
 #define MSG_ZPROBE_OUT  "Z probe out. bed"

is thrown when the probe will not hit the bed when driven down.

**Comment by Wackerbarth** [comment]
I interpret that remark to be "Probe is out of bounds"

**Comment by AnHardt** [comment]
@Wackerbarth 
If i remember correct the web gui is only able to tag the current state.
If the tag already exists, but is not visible in the web gui you can simply put in its name.
All collaborators have enough rights to do that.

How to push the local tags upstream:
```
git tag -a 1.0.1 9fceb02
git push origin :refs/tags/1.0.1
```

**Comment by Wackerbarth** [comment]
I'm referring to LABELS on the PR's and ISSUES on the MarlinDev GitHub.

**Comment by AnHardt** [comment]
@Wackerbarth 
Sorry for the missunderstandin.
The edit function for these colored stickers seems to be currently broken on GitHub. Can't edit them in my own repository.

**Comment by boelle** [comment]
about the labels on issues etc... there are approx 20-25 right now... i guess the work from top level too

**Comment by boelle** [comment]
i can edit them... @AnHardt are you still not able to?

info on how to do it: https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by boelle** [comment]
about the editing.. it says i need push access.... very odd with owner status that i dont have it...

will figure it

**Comment by boelle** [comment]
it says i need push access to danish branch, and that one we dont have.... but i guess i can merge this one and then edit? @Wackerbarth @AnHardt what you think?

**Comment by AnHardt** [comment]
@boelle 
>  i guess i can merge this one and then edit?

Yes, you can.
At the moment this is one of @Wackerbarth branches. You have no write access to his branches - thats normal.

About the labels. It works again for me. Maybe you have to be, not only an owner, but also a Collaborator.

**Comment by boelle** [comment]
with the labels.... i can edit both as owner and collab.... i think it was a temp thing??

**Comment by boelle** [comment]
the persmission system works so that if you are a owner you dont need to be collab... its only a few extra advantages i get by the owner status... i only have it as i'm more availble than ErikZalm  and daid

**Comment by boelle** [comment]
merging this one so i can edit the rest

**Pull request merged**
