### PR TITLE
Remove extra Allenkey examples from Delta configs

### PR DESCRIPTION
**Pull request by thinkyhead**
As noted by @o-lampe at https://github.com/MarlinFirmware/MarlinDev/issues/114#issuecomment-136757614 the `MANUAL_FEEDRATE` for Delta Z should be the same as XY.

### CODE REVIEW

**Comment by thinkyhead** [comment]
> Wouldn't it be better…?

Indeed, and done!

**Comment by taalabash** [comment]
Thank you for this really fast fix!!  :)

**Comment by clefranc** [comment]
@thinkyhead I can't understand why there is 3 copy of the Z_PROBE_ALLEN_KEY deploy and stow in the delta configuration files. One generic, one for Kossel mini and one for pro...

**Comment by thinkyhead** [comment]
@clefranc Originally there was only one delta configuration. As these were split up by the contributors, some of them altered the existing options while others simply un-commented the one appropriate to the specific robot. At present you can think of all the ones that are commented-out as alternative examples. But, I'm all for having only a single set of options and removing the commented-out ones, since that's the point of the examples — to give the most likely default settings for a specific design.

**Comment by Wackerbarth** [comment]
The remaining changes here now have nothing to do with feed rate.

All that is left here is the removal of some Allen Key movement specifications.

These should NOT be removed until we address the greater issue of how we handle ALL similar configuration situations.

This should be done as a part of the reorganization for Marlin 1.2

In particular, although I agree that the individual examples should not have all of the alternatives, we do need to have a reference document which has the information appropriate to assist a user in configuraing his own.

**Comment by thinkyhead** [comment]
Cleaning up lingering branches… The name of this PR has been changed, and it's still the right idea.

Someone else will need to create a new PR for this, as my fork will not be accepting any commits that were made after September 14th.

**Comment by Roxy-3DPrintBoard** [comment]
> thinkyhead commented 26 days ago
>@clefranc Originally there was only one delta configuration. As these were split up by the contributors, some of them altered the existing options while others simply un-commented the one appropriate to the specific robot. At present you can think of all the ones that are commented-out as alternative examples.

The big problem with the AllenKey stuff is it only handles specific implementations right now.  One big weakness is there is no concept of the AllenKey having to be deployed (and retracted) manually.  I'm bringing up the Release Candidate on my new G2s Delta kit and having to make changes to handle that issue.

**Comment by clefranc** [comment]
@Roxy-3DPrintBoard Resurrecting this *old* thread:
https://github.com/MarlinFirmware/MarlinDev/issues/61#issuecomment-137518095

Basically, you have the same manual dock/stow probe than me. Solved this issue with added start G-code in my slicer.

**Comment by Wackerbarth** [comment]
Superseded -- The removal of the inactive key motion sequences is a natural byproduct of the new configuration approach.

**Pull request closed without merging**
