### PR TITLE
Rename numbered travis tests to something meaningful

### PR DESCRIPTION
**Pull request by AnHardt**
Rename Travis Tests to more descriptiv names.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
This will require a corresponding change to the boards.txt in the support platform.
I'll work on that part of it.

**Comment by Wackerbarth** [comment]
@AnHardt -- Now that the Arduino IDE 1.6.6 has been released, I think we should move to using it for our Travis tests and drop support for all prior versions of the IDE. Do you agree?

**Comment by AnHardt** [comment]
Thanks.
Yes. The actual release of Arduino (1.6.6) is the easiest one to access for the 'users'. We should test with this.

**Comment by AnHardt** [comment]
Only the actual `release` and `1.0.x` branch work better with ARDUINO 1.0.6 under certainly circumstances (dual extruder).

**Comment by AnHardt** [comment]
Update done.

**Comment by Wackerbarth** [comment]
@AnHardt  -- "Only the actual release and 1.0.x branches work better with ARDUINO 1.0.6 under certain circumstances (dual extruder)."

I'm going to open a separate issue to discuss this.

**Comment by Wackerbarth** [comment]
See PR #276

**Pull request closed without merging**
