### PR TITLE
Fix endless loops from "Fix AutoBedLevel Bug #33"

### PR DESCRIPTION
**Pull request by AnHardt**
And some minor optimizations for the inverse matrix z-correction code.

Combined two loops over the bedlevel data.
Eliminated some rarely used variables.
Use min() and max() macros.
A bit of spacing to find the relevant code in the output loops.

Output is now:
```
#define Z_PROBE_OFFSET_FROM_EXTRUDER -0.85

23:34:30.906 : N16 G29 V4 *71
23:34:30.924 : G29 Auto Bed Leveling
23:34:35.033 : Bed X: 10.000 Y: 51.000 Z: 0.836
23:34:38.112 : Bed X: 100.000 Y: 51.000 Z: 0.838
23:34:41.142 : Bed X: 190.000 Y: 51.000 Z: 0.903
23:34:44.682 : Bed X: 10.000 Y: 120.000 Z: 0.884
23:34:47.730 : Bed X: 100.000 Y: 120.000 Z: 0.858
23:34:50.764 : Bed X: 190.000 Y: 120.000 Z: 0.843
23:34:54.278 : Bed X: 10.000 Y: 189.000 Z: 0.882
23:34:57.329 : Bed X: 100.000 Y: 189.000 Z: 0.842
23:35:00.388 : Bed X: 190.000 Y: 189.000 Z: 0.729
23:35:00.403 : Eqn coefficients: a: -0.00023565 b: -0.00030012 d: 0.90566310
23:35:00.403 : planeNormal x: 0.000236 y: 0.000300 z: 1.000000
23:35:00.407 : +-----------+
23:35:00.407 : |...Back....|
23:35:00.407 : |Left..Right|
23:35:00.408 : |...Front...|
23:35:00.410 : +-----------+
23:35:00.410 : Measured Bed Topography:
23:35:00.410 : +0.88150 +0.84225 +0.72925
23:35:00.413 : +0.88425 +0.85775 +0.84250
23:35:00.413 : +0.83625 +0.83800 +0.90300
23:35:00.413 : Corrected Bed Topography:
23:35:00.427 : +0.15225 +0.11300 +0.00000
23:35:00.427 : +0.15500 +0.12850 +0.11325
23:35:00.428 : +0.10700 +0.10875 +0.17375
23:35:00.428 : Corrected Bed Topography in new coordinates:
23:35:00.428 : +0.10983 +0.09179 +0.00000
23:35:00.428 : +0.09187 +0.08658 +0.09254
23:35:00.430 : +0.02317 +0.04612 +0.13233
23:35:00.430 : Height from Bed to Nozzle
23:35:00.430 : (+) above, or (-) below surface :
23:35:00.433 : +0.02250 +0.04054 +0.13233
23:35:00.433 : +0.04046 +0.04575 +0.03979
23:35:00.441 : +0.10917 +0.08621 +0.00000
23:35:00.441 : 
23:35:00.441 : Bed Level Correction Matrix:
23:35:00.442 : +1.000000 +0.000000 -0.000236
23:35:00.442 : -0.000000 +1.000000 -0.000300
23:35:00.446 : +0.000236 +0.000300 +1.000000
23:35:00.446 : ok
```

Works. At least compiles, has no endless loops and did not destroy the printer.
I did not feel a difference between the z-heights of G28 and G29. But normally i don't.
I corrected my z-height about 0.05mm, but that's about the normal amount.

I do not see much of advantage. As long as we determine our Z_PROBE_OFFSET_FROM_EXTRUDER manually - by test, these little correction is included in the Z_PROBE_OFFSET_FROM_EXTRUDER.

But form your own view.

@boelle 
This is code to test. Please don't merge (now).

### CODE REVIEW

**Comment by setar** [comment]
This code adjusted my max bed hight from 0.98543 to 0.74365
note -  original position Z was not known, and using it saves time (i use homing to  z_max_endstop and Z axis is very slow)

<pre>
SENDING:G29 V4
G29 Auto Bed Leveling
Bed X: 0.000 Y: 0.000 Z: -20.587 FSR: 893
Bed X: 187.000 Y: 0.000 Z: -20.506 FSR: 893
Bed X: 374.000 Y: 0.000 Z: -21.429 FSR: 895
Bed X: 0.000 Y: 145.000 Z: -20.961 FSR: 896
Bed X: 187.000 Y: 145.000 Z: -20.922 FSR: 895
Bed X: 374.000 Y: 145.000 Z: -21.273 FSR: 895
Bed X: 0.000 Y: 290.000 Z: -21.492 FSR: 895
Bed X: 187.000 Y: 290.000 Z: -20.951 FSR: 894
Bed X: 374.000 Y: 290.000 Z: -21.410 FSR: 895
Eqn coefficients: a: -0.00095601 b: -0.00153042 d: -20.65832328
planeNormal x: 0.000956 y: 0.001530 z: 1.000000
rot_min_diff=-21.07109
rot_max_diff=-20.32744
difference=0.74365
+-----------+
|...Back....|
|Left..Right|
|...Front...|
+-----------+
Measured Bed Topography:
 -21.49168 -20.95148 -21.41015
 -20.96057 -20.92236 -21.27300
 -20.58694 -20.50625 -21.42867

Corrected Bed Topography:
 +0.00000 +0.54019 +0.08153
 +0.53111 +0.56932 +0.21867
 +0.90473 +0.98543 +0.06300

Corrected Bed Topography in new coordinats:
 +0.02327 +0.74224 +0.46234
 +0.33247 +0.54945 +0.37758
 +0.48418 +0.74365 +0.00000

Height from Bed to Nozzle :
 (+) is airprinting, (-) is touch under bed surface
 +0.72038 +0.00142 +0.28131
 +0.41118 +0.19420 +0.36607
 +0.25947 +0.00000 +0.74365
current_position[Z_AXIS]=-0.28131
</pre>

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/MarlinDev/pull/40#issuecomment-127611892

@setar 
Can you print with a remaining z-height-error of more than 0.7 mm?

**Comment by setar** [comment]
No, but I'm working on this issue.
I have a large printer (300x400x400), and fixed bed, which is why I need a curvature compensation algorithm

**Comment by AnHardt** [comment]
Have you tried MANUAL_BED_LEVELING and or MESH_BED_LEVELING? At least it's worth to have a look at those.

**Comment by setar** [comment]
Of course, I tried it and was not successful (at the junction of the grid movement is obtained with a crunch)

**Comment by Wackerbarth** [comment]
@setar -- What kind of kinematics are you using?  The error seems to be (generally) hyperbolic in nature.
That indicates a mechanical misalignment that you might be able to improve by adjustment.

What kind of readings do you get from a 5x5 or 7x7 mesh?

**Comment by RicardoGA** [comment]
I'm currently testing this PR, i'll let you know how it goes after some prints

**Comment by setar** [comment]
@Wackerbarth
I use classical kinematics with movable table similar mendel90 only larger.
I tried 3x3 and 5x5 of the matrix grid with the same result.
These days try to just 2 and record video

**Comment by RicardoGA** [comment]
After some prints everything seems working ok. here's my g29 log 

16:07:56.338 : G29 Auto Bed Leveling
16:08:03.104 : Bed X: 40.000 Y: 30.000 Z: 6.317
16:08:08.203 : Bed X: 97.000 Y: 30.000 Z: 6.333
16:08:13.313 : Bed X: 154.000 Y: 30.000 Z: 6.277
16:08:19.172 : Bed X: 40.000 Y: 97.000 Z: 6.285
16:08:24.235 : Bed X: 97.000 Y: 97.000 Z: 6.338
16:08:29.379 : Bed X: 154.000 Y: 97.000 Z: 6.293
16:08:35.255 : Bed X: 40.000 Y: 164.000 Z: 6.281
16:08:40.313 : Bed X: 97.000 Y: 164.000 Z: 6.332
16:08:45.407 : Bed X: 154.000 Y: 164.000 Z: 6.318
16:08:45.423 : Eqn coefficients: a: 0.00001096 b: 0.00001057 d: 6.30602407
16:08:45.423 : planeNormal x: -0.000011 y: -0.000011 z: 1.000000
16:08:45.423 : +-----------+
16:08:45.423 : |...Back....|
16:08:45.423 : |Left..Right|
16:08:45.423 : |...Front...|
16:08:45.423 : +-----------+
16:08:45.423 : Measured Bed Topography:
16:08:45.423 : +6.28125 +6.33150 +6.31825
16:08:45.439 : +6.28525 +6.33750 +6.29250
16:08:45.439 : +6.31700 +6.33325 +6.27650
16:08:45.439 : Corrected Bed Topography:
16:08:45.439 : +0.00475 +0.05500 +0.04175
16:08:45.439 : +0.00875 +0.06100 +0.01600
16:08:45.439 : +0.04050 +0.05675 +0.00000
16:08:45.439 : Corrected Bed Topography in new coordinates:
16:08:45.439 : +0.00458 +0.05421 +0.04033
16:08:45.439 : +0.00929 +0.06092 +0.01529
16:08:45.454 : +0.04175 +0.05737 +0.00000
16:08:45.454 : Height from Bed to Nozzle
16:08:45.454 : (+) above, or (-) below surface :
16:08:45.454 : +0.05633 +0.00671 +0.02058
16:08:45.454 : +0.05163 +0.00000 +0.04562
16:08:45.454 : +0.01917 +0.00354 +0.06092
16:08:45.454 : 
16:08:45.454 : Bed Level Correction Matrix:
16:08:45.454 : +1.000000 +0.000000 +0.000011
16:08:45.454 : -0.000000 +1.000000 +0.000011
16:08:45.470 : -0.000011 -0.000011 +1.000000

**Comment by AnHardt** [comment]
@RicardoGA 
Thank you for the test.
Did you notice any positive effect - besides of the altered output?

**Comment by RicardoGA** [comment]
@AnHardt 
At the moment no. After the last bug fix (Homing & Leveling Bugs #2040) the autobed level was working good on my printer but i´m going to keep testing and if i notice something i´ll let you know

**Comment by Wackerbarth** [comment]
@AnHardt  -- What is the status of this change?  Was some, or all of it incorporated into another PR?
Is there still something we need to add?

**Comment by RicardoGA** [comment]
@Wackerbarth i just check the latest branch and still does not incorporate the changes of this pull request

**Comment by Wackerbarth** [comment]
Speciffically, what does this change that is not in the current "master"?

**Comment by RicardoGA** [comment]
@Wackerbarth  what it changes its the way it find the max, min and the difference but i wouldn't merge it until more people test it, especially when the current auto bed leveling isn't working.

because since the last bug hunting the current bed leveling it's working ok for the most printers configurations.

**Comment by Wackerbarth** [comment]
Perhaps I don't understand.  Max, Min and difference are mathematically defined terms. What difference does it make HOW the code searches to find these values?  To me, it seems that you still have to arrive at the same answer (otherwise, one of the methods was in error and did not really find the value that it claims to find)

**Comment by RicardoGA** [comment]
i agree, mathematically you can find a value with different methods and the way you find it does not make difference, to me this pull request only make sense if it works with the cases that the current version doesn't, otherwise i wouldn't change it.

that's why i say that need to be tested in that cases

**Comment by Wackerbarth** [comment]
So, are you saying that the current code fails to provide the correct result in some/all cases?

**Comment by Wackerbarth** [comment]
@AnHardt  -- Is this issue "dead"?  We need either to incorporate it because it is need ed, or close it because it adds no value.

DEADLINE -- 2015 Sep 11

**Comment by setar** [comment]
not farsighted :)

**Comment by Wackerbarth** [comment]
No one followed up on this.  If you care to reopen it, please do so AFTER we release RC1.

**Pull request closed without merging**
