### PR TITLE
Easy Bed Leveling Rectangle

### PR DESCRIPTION
**Pull request by IamTheVector**
This edit is made to solve the  awkward method actually used to find the right probing square. This edit let the user make use of the X and Y value printed on screen on the GUI and find the lower leftmost point and the rightmost top point of the square in wich to probe. The process is simple. 

-Home Axis and rise the Z to let the space for the probe
-Extend the probe
-Bring the probe where you want the leftmost front point. Use m114 to print the actual position write down X and Y value. 
-Write X and Y value in the POS_A_X and POS_A_Y 
-Bring the probe where you want the rightmost back point. Use m114 to print the actual position write down X and Y value. 
-Write X and Y value in the POS_B_X and POS_B_Y 
- Still , every value has  to be consistent. You cant probe a point that your probe can't reach.  
End. ( Explaination video incoming )

### CODE REVIEW

**Comment by Sniffle** [comment]
The problem with this configuration for decining the probe area is the
assumption that all home positions are in the front right.  This isnt
always the case as one of my printers home is in the back left.

**Comment by IamTheVector** [comment]
Yeah thanks Sniffle, i think you are right. I just tought this solution, but i have to verify, but i think it should do the trick. 

 #define LEFT_PROBE_BED_POSITION  (POS_A_X-X_PROBE_OFFSET_FROM_EXTRUDER*X_HOME_DIR)
 #define FRONT_PROBE_BED_POSITION (POS_A_Y-Y_PROBE_OFFSET_FROM_EXTRUDER*Y_HOME_DIR)
 
 #define RIGHT_PROBE_BED_POSITION (POS_B_X-X_PROBE_OFFSET_FROM_EXTRUDER*X_HOME_DIR)
 #define BACK_PROBE_BED_POSITION  (POS_B_Y-Y_PROBE_OFFSET_FROM_EXTRUDER*Y_HOME_DIR)

**Comment by IamTheVector** [comment]
How you achieve this configuration usually? By using MAX Home endstops, or just reversing the movements of you axis? 

Code talking:
#define X_HOME_DIR
or 
#define INVERT_X_DIR

**Comment by Sniffle** [comment]
Moving the endstops and inverting the direction

**Comment by IamTheVector** [comment]
I actually tried to solve the issue you found that was reasonable and understandable... i made math and sign inversion with if statement just to find out that it works with the same expression.

**Comment by Sniffle** [comment]
The thing is, there isnt a good way to go about normalizing the numbers
because you never know how the printer is going to be setup and you dont
inherently know which way the motors will spin... At least in software...

**Comment by IamTheVector** [comment]
It's not a big issue. I can make if statement based on motor direction and endstop direction or both. The fact is it seems that is not necessary. I Just tried with upper rightmost endstop by reversing motors. And it works.

**Comment by IamTheVector** [comment]
I tried every homing configuration with every probe position. This is working. Tomorrow i will make a small tutorial.

**Comment by boelle** [comment]
could this PR be rebased against RCbugfix on the main repro? we are going to cut this repro loose as it just adds to the confusion

**Comment by jbrazio** [comment]
The **MarlinDev** repository will soon be deleted, you should first check if the functionality proposed on this PR is already present on the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) and if not rebase and reopen this PR at the [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin) repository against the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) for proper followup from the development team.

Thank you for your interest making Marlin better.

**Pull request closed without merging**
