### PR TITLE
High temp thermistor

### PR DESCRIPTION
**Pull request by JeanSebastienCarrier-Dyze**
These modifications allow the use of high temperature thermistors in order to handle hot ends temperature up to 500 degrees Celsius.

Because thermistors able to read higher temperature tend to have a hard time reading lower values, two "defines" were added to allow a "preheating time" as well as handle some measure of noise reading (sudden drops for a few frames).

These defines have been added to the default configuration. Using another configuration or commenting these additions produce the same execution than before these changes.

A high temperature compatible thermistor has been added (no 66) to the thermistor table

### CODE REVIEW

**Comment by JeanSebastienCarrier-Dyze** [comment]
It's been some times since I created this pull request, and I haven't received any feedback yet. So I'm wondering if there's something I should have done or if there's something I can do to help.

**Comment by JeanSebastienCarrier-Dyze** [comment]
Checking the "contributing" section of the wiki, I realized I didn't post the hardware used for testing, as well as the tests that were conducted.

The tests were taken from https://github.com/MarlinFirmware/Marlin/issues/2066
The hardware was : Board: Arduino MEGA2560 with RAMPS 1.4

**TEST 7 - Hotend's thermistor disconnected before startup**
No error is shown. Temperature shown is 20°C, 1°C below the mintemp error.
Since the conditions «is preheating» and «target temperature > 0» is not met, the min_temp error is not shown as it would normally be.

**TEST 9 - Hotend's thermistor disconnected after heating begins AND before (preheating time) seconds elapsed**
Heater remains ON for the duration of "preheating time". Turns OFF once the duration is elapsed.

**TEST 11 - Hotend's thermistor disconnected after heating begins AND after (preheating time) seconds elapsed**
Min_temp error, heater is disabled.

**TEST 13 - Hotend's thermistor disconnected after target temperature reached.**
Min_temp error, heater is disabled.

**Comment by jbrazio** [comment]
The **MarlinDev** repository will soon be deleted, you should first check if the functionality proposed on this PR is already present on the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) and if not rebase and reopen this PR at the [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin) repository against the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) for proper followup from the development team.

Thank you for your interest making Marlin better.

**Comment by JeanSebastienCarrier-Dyze** [comment]
I did a pull request on MarlinFirmware/Marlin a few months ago, https://github.com/MarlinFirmware/Marlin/pull/2941#issuecomment-211174843
before being told that I should instead do it in marlin dev. I'm not sure I understand on which repo I should be working and why?

**Comment by jbrazio** [comment]
Development methodology changed.
From now on we will have only one repo.

**Pull request closed without merging**
