### PR TITLE
warn if controller is incompatible with servo library

### PR DESCRIPTION
**Pull request by chris-bo**
Servos need a controller with at least two 16 bit timers to work.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
There is no reason to attempt to name the particular mcu's that have the necessary timer.
The compiler provides a symbol for each timer. So, if you want this extra "hint", just check for the existence of the necessary timer symbol. That way, if some new device comes along, your check will still be correct.

**Comment by chris-bo** [comment]
I copied the available options in Marlins servo.h. 

If you have any other mcu or some new device, the servo library uses timer1 as default.
However in Marlin timer1 is occupied by stepper functions so this line is commented out.
As a result the everything compiles fine, but the servos simply won't work.

If we want to keep this more generic, servo.h needs to be updated.
Maybe we could use timer3 as default and check for timer3?

**Comment by chris-bo** [comment]
But can we be sure, that timer3 is always 16 bit?

**Comment by boelle** [comment]
could this PR be rebased against RCbugfix on the main repro? we are going to cut this repro loose as it just adds to the confusion

**Comment by jbrazio** [comment]
The **MarlinDev** repository will soon be deleted, you should first check if the functionality proposed on this PR is already present on the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) and if not rebase and reopen this PR at the [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin) repository against the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) for proper followup from the development team.

Thank you for your interest making Marlin better.

**Pull request closed without merging**
