### PR TITLE
Fix DUAL_X_CARRIAGE motor enabling

### PR DESCRIPTION
**Pull request by thinkyhead**
As noted by @darkjavi et.al. in #103, the E1 motor was not being enabled in `planner.cpp` when using `DUAL_X_CARRIAGE`. This patch enables and disables E1 as it should.

### CODE REVIEW

**Comment by darkjavi** [comment]
Nice, I'been out for a week. Now I'm back and can try this on the dual carriage machines.

The proposed fix is the very same that I had here working, except for the adition of  +  extern bool extruder_duplication_enabled; . So I'm positive that it'll work.

About what you where wondering in the other post about whether or not to include:
  if (extruder_duplication_enabled) g_uc_extruder_last_move[1] = BLOCK_BUFFER_SIZE * 2;

Not sure about that, I think the second extruder is now being handled in stteper.h:42 

    #define E_STEP_WRITE(v) { if(extruder_duplication_enabled) { E0_STEP_WRITE(v); E1_STEP_WRITE(v); } else if(current_block->active_extruder == 1) { E1_STEP_WRITE(v); } else { E0_STEP_WRITE(v); }}

I'll download your pr and give it a try on the dual carriage machines.

**Comment by thinkyhead** [comment]
@darkjavi Looking forward to your result. I'm just refreshing all my PRs to make sure they're still viable.

**Comment by darkjavi** [comment]
I was working on it yesterday, tested the pr and it didn't work, e1 was not enabling in duplication mode.
Took a look and realized that the
 g_uc_extruder_last_move[1] = BLOCK_BUFFER_SIZE * 2; 
it's a must, otherwise the code following that block will disable E1:

```C
          #if EXTRUDERS > 1
            if (g_uc_extruder_last_move[1] == 0) disable_e1();
```
As a dual carriage has 2 extruders,that code is being executed too, and it disables e1 as g_uc_extruder_last_move[1] hasn't been loaded anywhere.

Also realized that there is no need to do the disable_e1 on the dual_x_carriage exception cos that is been taken care by that same code.

I made a simple pr with a working fix https://github.com/Moebyus/MarlinDev/commit/82488436a0eec5cd3e5e8e5babcaf35cae6e8c60

```C
         case 0:
           enable_e0();
           g_uc_extruder_last_move[0] = BLOCK_BUFFER_SIZE * 2;
          #if ENABLED(DUAL_X_CARRIAGE)
            if (extruder_duplication_enabled) {
              enable_e1();
              g_uc_extruder_last_move[1] = BLOCK_BUFFER_SIZE * 2;
            }
           #endif
          #if EXTRUDERS > 1
            if (g_uc_extruder_last_move[1] == 0) disable_e1();
```

This just enables e1 and loads g_uc_extruder_last_move[1] if in duplication mode, the disabling of e1 will happen as it used to be.

About planner.cpp@113, I'm curious is there any reason that 
+uint8_t g_uc_extruder_last_move[4] = { 0 };
is not 
+uint8_t g_uc_extruder_last_move[EXTRUDERS] = { 0 };

**Comment by thinkyhead** [comment]
Thanks for the feedback. I've updated the PR — and you're correct that `g_uc_extruder_last_move[EXTRUDERS]` should be fine.

**Comment by darkjavi** [comment]
Compiled it, loaded and tested: It's working :)

**Comment by thinkyhead** [comment]
@darkjavi Sorry this didn't get merged before September 15th.

For the time-being, the last commit I can accept into my fork is https://github.com/MarlinFirmware/MarlinDev/commit/5e36b646351425d24a20850606bd478bb7e17970 from September 14th, so someone with a current branch will need to create a new PR with these changes if they are to be included in the upcoming release.

**Comment by Wackerbarth** [comment]
Integrated

**Pull request closed without merging**
