### PR TITLE
dx, dy, dz and de from float -> long

### PR DESCRIPTION
**Pull request by Wurstnase**
they are long, so they don't need to be float.

### CODE REVIEW

**Comment by Wurstnase** [comment]
works on my coreXY

**Comment by Wurstnase** [comment]
works? works not? I can't say. I've got some issues with magically loosing steps and maybe this was the issue.

**Comment by Wurstnase** [comment]
I'm a rookie... It was a mechanical issue. So this should work.

**Comment by Wackerbarth** [comment]
Replaced by #297

**Pull request closed without merging**
