### PR TITLE
Add support for MAX31855 thermocouple IC

### PR DESCRIPTION
**Pull request by reidrankin**
The MAX31855 is a more precise version of the already-supported MAX6675
chip, so the same code paths are used.

### CODE REVIEW

**Comment by reidrankin** [comment]
Rebased and restyled.

**Comment by Grogyan** [comment]
Only works when SDSUPPORT is enabled

**Comment by KiteLab** [comment]
@Grogyan 
Is that a MAX31855 only problem, or also true for MAX6675?

**Comment by KiteLab** [comment]
The problem could be around
https://github.com/MarlinFirmware/MarlinDev/blob/master/temperature.cpp#L907

**Comment by Grogyan** [comment]
@KiteLab That line is correct, as the condtionals.h file keeps it enabled. regardless whether it is a MAX6675 or MAX31855.
The problem is only appearing with the MAX31855

**Comment by Grogyan** [comment]
I should point out that I manually made the changes of this pull request and applied to RC2, as I wasn't aware of the Dev repository.
Travis (GIT BOT) says that there is conflicts with merging this pull request to the main Dev branch

**Comment by reidrankin** [comment]
Yeahhh... They made some major changes a couple months ago to the dev
branch and I haven't had time to rebase. I guess I'd better get on that!

**Comment by thinkyhead** [comment]
I made MarlinFirmware/Marlin#3112 before I realized this PR was hanging around. How do they compare?

**Comment by Grogyan** [comment]
The old pull request does not work with the current changes. And took a
fair bit of fiddling with the code for my copy from October last year.

**Comment by Grogyan** [comment]
What I was meant to say is that although the changes are similar to #3112,
#193 worked a long time ago with a little bit of fiddling.

As #3112 is essentially an updated version of #193,  and will test it out
this weekend (hopefully). #3112 should be used over #193.

**Comment by thinkyhead** [comment]
This PR needs to be redone against the `dev` branch, so I'm closing this one.

**Pull request closed without merging**
