### PR TITLE
Set Extruder Offsets on an LCD Controller and Save to EEPROM

### PR DESCRIPTION
**Pull request by gralco**
Title says it all.

### CODE REVIEW

**Comment by oysteinkrog** [comment]
Please fix the commit message to describe the changes.

**Comment by thinkyhead** [comment]
This is a subtle thing, but it's a good idea to always write the same number of values out to EEPROM even if the number of extruders differs. That way the EEPROM values always align, even if yuo re-flash with more or fewer extruders. So in this case, it should always write out and read 4 extruder offsets. When writing them, just use zeros for the unused ones. When reading them, you shouldn't need to to anything special, just read all 4. Also, when making any change to EEPROM, always bump the version number. I think the next one is "V21".

**Comment by gralco** [comment]
@thinkyhead
That makes sense, so how's the recent commit?

**Comment by thinkyhead** [comment]
@Wackerbarth Yes, in fact that's the idea. The global array only needs to be as long as necessary to store the offsets per extruder. The EEPROM write function then pads out the data using a temporary var, and the EEPROM read function reads the values into a dummy var before storing (or not storing) them to the global array.

**Comment by Wackerbarth** [comment]
Agreed.But, unless I misread the proposed code, it actually allocates RAM to all possible variables.

**Comment by Wackerbarth** [comment]
And along with that, we should pre-allocate space for 11 variables to describe the delta Space, (whichI think exceeds the number needed for CoreXX and Cartesian systems).

**Comment by boelle** [comment]
could this PR be rebased against RCbugfix on the main repro? we are going to cut this repro loose as it just adds to the confusion

**Comment by studiodyne** [comment]
Hi ,
Can you make the added code to make a Configurator switch
To switch from chimera to cyclops hotend or diamond = LCDgralcomenu 'for equal offsets ' + ' Heater1/sensor1 equals Heater0/sensor0 ... to trick the sofware '

For the moment , if we want to switch between cyclops and chimera , we have to re'firm' the board
Can you make us , a Switch Menu to swap between our configuration or , just add  a LCD HEATER trick menu 
i'm sure i will be good in programmation in the future but for the moment , i need help 
thks

**Pull request closed without merging**
