### PR TITLE
Update MarlinDev with all updates from RCBugFix

### PR DESCRIPTION
**Pull request by thinkyhead**
- All in one large commit, for testing purposes only. Don't merge!

### CODE REVIEW

**Comment by Sniffle** [comment]
You poor thing... Good luck

**Comment by thinkyhead** [comment]
I think it will be easier to just rearrange `RCBugFix` into folders in the style of `MarlinKimbra` and then piecemeal bring in the fancy new things loitering in `dev` such as that new experimental configuration system.

**Comment by jbrazio** [comment]
I agree @thinkyhead.

**Comment by thinkyhead** [comment]
@jbrazio Yes, and that way we also can preserve the full commit history (maybe even PR merge commits) as it is.

**Pull request closed without merging**
