### PR TITLE
Unique LiquidCrystal library.properties name

### PR DESCRIPTION
**Pull request by per1234**
Use unique name value in library.properties for the LiquidCrystal library. This solves the issue of the LiquidCrystal library always appearing as Type: Updatable in the Arduino IDE 1.6.6 Library Manager when a Marlin board is selected(https://github.com/arduino/Arduino/issues/4307). This is caused by Library Manager getting confused by the LiquidCrystal library included with the Marlin boards package having the same name as the LiquidCrystal library included with the Arduino IDE.

If this is the wrong branch to submit this PR to please let me know and I'll resubmit to the correct branch.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
@per1234 -- The branch is fine.

However, we need to have a discussion about the "right " way to address the problem.
So, is our version of Liquid Crystal just an older (different ?) one? Or is it, in some way, "better" (preferred for inclusions in our builds?
If the latter, then we certainly need to rename and distribute it as a differently named library.

However, if the library is actually "the same", then I'm not sure what we should do.
On one hand, there is an argument for using "the latest" released version of the library.
But then, we have all experienced library compatibility issues.

But even if everything is the same and we SHOULD be using the latest, how should we distribute it.
Some will argue that it is better for us to "package it all up into just one download".
Others might argue that we should use the library manager to handle that downloading and upgrading.
But that might be more steps for the unsophisticated user.

DISCUSSION PLEASE

**Comment by per1234** [comment]
>So, is our version of Liquid Crystal just an older (different ?) one?

I just did a diff against the LiquidCrystal 1.0.1 included with Arduino IDE 1.6.4 and the LiquidCrystal included with Marlin is identical.

>But then, we have all experienced library compatibility issues.

If you decide that you want control of which version of the libraries are used with Marlin then you should also be aware of https://github.com/arduino/Arduino/issues/4064. Libraries installed using Library Manager are installed to the sketchbook libraries folder where they override the libraries bundled with boards packages.

**Comment by Wackerbarth** [comment]
@Roxy-3DPrintBoard  @KiteLab @a4jp-com @AnHardt @thinkyhead 

I would like to see some discussion of this issue. Since it appears that we are using "stock" Arduino code, we could go either way.

Should we:
1) Rename the library and distribute that as a part of Marlin support.
2) Leave it the same name, distribute it, and have the users who also download the standard library to their sketchbook get "duplicate library" warnings
3) Require that each user download the standard Arduino library (It's not difficult. But it is an additional step)
4) Rewrite (and maintain) a fast_io equivalent to this library
5) Some other suggestion

**Comment by a4jp-com** [comment]
2. I think it is nicer to have everything in the one place with the duplicate warnings. It is easy just to delete the files not needed, and the program still works even if it has a duplicate file or duplicates.

**Comment by Roxy-3DPrintBoard** [comment]
My thinking goes like this:

When you download Marlin to build it, everything should be in place.   If
there is a duplicate, we should be prepared to give the user good guidance
on how to remove the complaint.   This has to be easy for people that don't
know anything about firmware tools.   We are trying to make sure Marlin can
be moved to or updated easily on any RepRap printer.   The focus should be
on making sure the most people have the least number of problems.

Conversely, if they already have a an LCD Library installed, they probably
are not an unwashed, simple, vanilla user of Arduino.   If we provide them
simple and clear directions on how to remove the conflict, they probably
can get through the process.

**Comment by a4jp-com** [comment]
Sounds good to me. ^^

**Pull request closed without merging**
