### PR TITLE
Update language_pt-br.h

### PR DESCRIPTION
**Pull request by hydrocat**
As far as I can tell, ISO10646 supports latin characters such as ã â á à and ç. However, if this is not the case, another fork should be done.
also, should this folow the same #ifndef #define structure found in the english version ?

### CODE REVIEW

**Comment by Wackerbarth** [comment]
"also, should this follow the same #ifndef #define structure found in the english version ?" --

`No. That structure is there only because English is the fall-back default. If you define the message in your native language file, then your version will get used. But if, for example, a new message is added (and your translation is not available) then there will still be an appropriate message (in English).
`

**Comment by Wackerbarth** [comment]
Since I don't know the language, would someone who does please review these translations so that we can confirm the accuracy of the changes and merge them into our development stream.

**Comment by AnHardt** [comment]
Some info about the LCD language system:
https://github.com/MarlinFirmware/Marlin/wiki/LCD-Language

Most of these (ã â á à and ç) don't make much sense on the Hitachi displays. Only the (rare) DISPLAY_CHARSET_HD44780_WESTERN displays provides the needed ROM. (https://www.sparkfun.com/datasheets/LCD/HD44780.pdf page 18)
The usual DISPLAY_CHARSET_HD44780_JAPAN will show crap only.

The perfect hardware for these chars are the full graphic displays.
I suggest to make a new language file `language_pt-br_utf.h`.
Use this header:
```
#define MAPPER_C2C3
// Define SIMULATE_ROMFONT to see what is seen on the character based display defined in Configuration.h
//#define SIMULATE_ROMFONT
#define DISPLAY_CHARSET_ISO10646_1
```

**Comment by boelle** [comment]
could this PR be rebased against RCbugfix on the main repro? we are going to cut this repro loose as it just adds to the confusion

**Comment by jbrazio** [comment]
The **MarlinDev** repository will soon be deleted, you should first check if the functionality proposed on this PR is already present on the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) and if not rebase and reopen this PR at the [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin) repository against the [RCBugfix branch](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) for proper followup from the development team.

Thank you for your interest making Marlin better.

**Pull request closed without merging**
